name: xAuthPremiumAutoLogin
main: me.kolorafa.bukkit.xAuthPremiumAutoLogin.XAuthPremiumAutoLogin
version: 1.3
description: Autologin and autoregister premium players at xauth
author: kolorafa
depend: [ PremiumProxy, xAuth ]
commands:
    xAuthPremiumAutoLogin_pass:
        usage: "Usage: /setpassword YourNewAccountPassword"
        aliases: setpassword
        description: Changes account password
